name: restaurant_app
description: A new Flutter project.
publish_to: 'none'
version: 1.3.0+6

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1
  http: ^1.1.0
  provider: ^6.1.1
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  intl: ^0.18.1
  flutter_local_notifications: ^16.1.0
  rxdart: ^0.27.7
  android_alarm_manager_plus: ^3.0.3
  device_info_plus: ^9.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.3
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/logo/logo.png'
  adaptive_icon_background: 'assets/logo/background.png'
  adaptive_icon_foreground: 'assets/logo/foreground.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/food.png
    - assets/images/drink.png
    - assets/images/search-restaurant.png
    - assets/images/not-found.png
    - assets/images/empty-data.png
    - assets/images/no-internet.png
    - assets/lotties/loading.json
    - assets/logo/logo.png