name: submissionyudhae01
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_native_splash: ^2.3.7
  flutter_svg: ^2.0.9
  geocoding: ^3.0.0
  go_router: ^13.2.0
  google_maps_flutter: ^2.6.0
  http: ^1.1.2
  image: ^4.1.7
  image_picker: ^1.0.7
  
  json_annotation: ^4.8.1
  location: ^6.0.1
  path: ^1.8.3
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
