name: flutstory
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  go_router: ^14.0.0
  fluttertoast: ^8.2.4
  http: ^1.2.1
  path: ^1.9.0
  path_provider: ^2.1.2
  http_parser: ^4.0.2
  image: ^4.1.7
  image_picker: ^1.0.7
  intl: ^0.18.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/illustrations/
    - assets/icons/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
