name: story_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  image_picker: ^1.0.5
  camera: ^0.10.5+7
  camera_web: ^0.3.2+3
  http: ^1.1.2
  image: ^4.1.3
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  google_maps_flutter_web: ^0.5.4+3
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  geocoding: ^2.1.1
  #hexcolor: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/